# Generated by Django 3.1.3 on 2023-02-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230219_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
    ]
